baseURL = "https://ramchaik.github.io/jamsite/"
languageCode = "en-us"
title = "JAMSite"
theme = "tale"
copyright = "Copyright 2021 ramchaik"
disableKinds=["section"]

[outputs]
  home = ["HTML", "JSON"]
